apiVersion: v1
kind: ResourceQuota
metadata:
  name: infrastructure-compute-limits
  namespace: core-infrastructure
spec:
  hard:
    pods: "20"
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
