apiVersion: vault.hashicorp.com/v1alpha1
kind: VaultSecretEngine
metadata:
  name: k8s-token-factory
  namespace: core-infrastructure
spec:
  path: "kubernetes"
  type: "kubernetes"
  description: "Dynamic target generation for service account infrastructure tokens"
  config:
    kubernetes_host: "https://kubernetes.default.svc:443"
