name: Go-Pulumi-Verification
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Go_Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        # ... rest of your toolchain steps
